# -*- coding: utf-8 -*-
"""codveda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XX-1xPVY19C0ihw4gWn9JFMWcO8B7FYW
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/3) Sentiment dataset.csv')

df.head(5)

df.tail()

df.shape

"""**1.summary of data**

this is a dataset about 732 people user useing different type of social media platform.this data 732 rows and 15 column all what is username, like, hastag and all about.there are many platform using this people.

**2. Column descriptions**

Text: write a sentense for your post basically discribe thing

Sentiment:sentiment is post emotion(ex.happy,love,..)

Timestamp:formatted date-time value used to record the occurrence of an event formats like YYYY-MM-DD HH:MM:SS

User: user name unique not duplicated

Platform:	there are there platform(Twitter,Instagram,Facebook) which platform use give data

Hashtags:	give hashtags on post

Retweets: reting on post

Likes: how many like in post

Country: give country name

Year: give year

Month: give month

Day: give day

Hour: give hour
"""

df.info()

df.isnull().sum()

df.duplicated().sum()

df.dtypes

df['Sentiment'].unique()

df['Sentiment'].value_counts()

df['Platform'].unique()

df['Platform'].value_counts()

df['Platform'] = df['Platform'].replace({' Twitter  ':' Twitter '})

df['Platform'].unique()

df['Platform'].value_counts()

df.describe()

import seaborn as sns
import matplotlib.pyplot as plt

"""**Sentiment Distribution**"""

sns.countplot(data=df, x='Sentiment', palette='coolwarm')
plt.title('Sentiment Distribution')
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.show()

"""**Tweets Over Time (by Hour or Day)**

**Hourly**
"""

df['Hour'] = df['Hour'].astype(int)
sns.countplot(data=df, x='Hour', palette='magma')
plt.title('Tweet Activity by Hour')
plt.xlabel('Hour of Day')
plt.ylabel('Number of Tweets')
plt.show()

"""**Daily**"""

sns.countplot(data=df, x='Day', palette='viridis')
plt.title('Tweet Activity by Day')
plt.xlabel('Day of Month')
plt.ylabel('Number of Tweets')
plt.show()

"""**Tweets by Country**"""

top_countries = df['Country'].value_counts().nlargest(10)

sns.barplot(x=top_countries.values, y=top_countries.index, palette='Set2')
plt.title('Top 10 Countries by Tweet Count')
plt.xlabel('Number of Tweets')
plt.ylabel('Country')
plt.show()

"""**Likes vs Retweets Scatter Plot**"""

sns.scatterplot(data=df, x='Retweets', y='Likes', hue='Sentiment', alpha=0.6)
plt.title('Likes vs Retweets')
plt.xlabel('Retweets')
plt.ylabel('Likes')
plt.show()

"""**Platform Usage**"""

sns.countplot(data=df, x='Platform', palette='pastel')
plt.title('Platform Distribution')
plt.xticks(rotation=45)
plt.xlabel('Platform')
plt.ylabel('Tweet Count')
plt.show()

"""**Correlation Heatmap**"""

df['Retweets'] = pd.to_numeric(df['Retweets'], errors='coerce')
df['Likes'] = pd.to_numeric(df['Likes'], errors='coerce')

corr = df[['Retweets', 'Likes', 'Hour', 'Day', 'Month']].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap')
plt.tight_layout()
plt.show()

"""**Word Cloud from Text**"""

from wordcloud import WordCloud

text_combined = ' '.join(str(t) for t in df['Text'].dropna())

wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text_combined)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud from Text')
plt.tight_layout()
plt.show()

"""**Regression Analysis**"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

df.sample(2)

df['Retweets'] = pd.to_numeric(df['Retweets'], errors='coerce')
df['Likes'] = pd.to_numeric(df['Likes'], errors='coerce')

df_reg = df[['Retweets', 'Hour', 'Day', 'Month', 'Likes']].dropna()

X = df_reg[['Retweets', 'Hour', 'Day', 'Month']]
y = df_reg['Likes']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R-squared Score:", r2_score(y_test, y_pred))

plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, alpha=0.6, color='hotpink')
plt.xlabel("Actual Likes")
plt.ylabel("Predicted Likes")
plt.title("Actual vs Predicted Likes")
plt.grid(True)
plt.show()

"""This scatter plot shows the relationship between actual and predicted likes. Each point represents a prediction, with actual likes on the x-axis and predicted likes on the y-axis. The points follow a strong diagonal trend, indicating good prediction accuracy. The plot is styled with a pink color and includes grid lines for better readability.

**Time Series Analysis**
"""

df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df = df.set_index('Timestamp')

# Daily count
daily_tweets = df['Text'].resample('D').count()https://app.powerbi.com

plt.figure(figsize=(12, 6))
daily_tweets.plot()
plt.title("Daily Tweet Frequency")
plt.xlabel("Date")
plt.ylabel("Tweet Count")
plt.grid(True)
plt.tight_layout()
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose

decomp = seasonal_decompose(daily_tweets, model='additive')

plt.figure(figsize=(12, 9))
decomp.plot()
plt.suptitle("Time Series Decomposition", fontsize=16)
plt.tight_layout()
plt.show()

"""**Clustering Analysis (K-
Means)**
"""

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

df_cluster = df[['Retweets', 'Likes', 'Hour', 'Day']].dropna()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_cluster)

inertia = []
k_range = range(1, 11)

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8, 4))
plt.plot(k_range, inertia, marker='o')
plt.title('Elbow Method For Optimal K')
plt.xlabel('Number of Clusters')
plt.ylabel('Inertia')
plt.grid(True)
plt.show()

# Let’s assume optimal k is 3
kmeans = KMeans(n_clusters=3, random_state=42)
df_cluster['Cluster'] = kmeans.fit_predict(X_scaled)

plt.figure(figsize=(8, 6))
sns.scatterplot(data=df_cluster, x='Retweets', y='Likes', hue='Cluster', palette='Set1')
plt.title('K-Means Clustering (Retweets vs Likes)')
plt.xlabel('Retweets')
plt.ylabel('Likes')
plt.grid(True)
plt.show()

df_cluster.groupby('Cluster').mean()

"""**Predictive Modeling: Classification**"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

df['Sentiment'] = df['Sentiment'].str.strip().str.lower()

positive_words = [
    'positive', 'joy', 'happiness', 'love', 'amusement', 'enjoyment',
    'admiration', 'affection', 'awe', 'surprise', 'acceptance',
    'adoration', 'anticipation', 'hope', 'kind', 'pride', 'elation',
    'euphoria', 'contentment', 'serenity', 'gratitude', 'inspiration',
    'enthusiasm', 'wonder', 'confidence', 'success', 'creativity',
    'celebration', 'freedom', 'motivation', 'satisfaction', 'blessed',
    'cheerful', 'joyful', 'overjoyed', 'ecstasy', 'romance', 'playful',
    'whimsy', 'fun', 'delight'
]

negative_words = [
    'negative', 'anger', 'fear', 'sadness', 'disgust', 'disappointed',
    'shame', 'despair', 'grief', 'loneliness', 'frustration', 'envy',
    'regret', 'helplessness', 'anxiety', 'resentment', 'sorrow',
    'hate', 'bad', 'boredom', 'betrayal', 'heartbreak', 'loss',
    'darkness', 'desperation', 'pain', 'isolation', 'obstacle',
    'pressure', 'embarrassed'
]

neutral_words = [
    'neutral', 'confusion', 'calmness', 'numbness', 'indifference',
    'reflection', 'contemplation', 'solitude', 'energy', 'emotion'
]

def map_sentiment(label):
    label = label.strip().lower()
    if label in positive_words:
        return 'Positive'
    elif label in negative_words:
        return 'Negative'
    elif label in neutral_words:
        return 'Neutral'
    else:
        return 'Neutral'

df['Sentiment_Cleaned'] = df['Sentiment'].apply(map_sentiment)
print(df['Sentiment_Cleaned'].value_counts())

from sklearn.preprocessing import LabelEncoder

df_class = df[['Retweets', 'Likes', 'Hour', 'Day', 'Platform', 'Sentiment_Cleaned']].dropna()

# Encode labels
le_sentiment = LabelEncoder()
df_class['Sentiment_Cleaned'] = le_sentiment.fit_transform(df_class['Sentiment_Cleaned'])

# Encode platform
le_platform = LabelEncoder()
df_class['Platform'] = le_platform.fit_transform(df_class['Platform'])

# Prepare features and target
X = df_class[['Retweets', 'Likes', 'Hour', 'Day', 'Platform']]
y = df_class['Sentiment_Cleaned']

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=le_sentiment.classes_))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=le_sentiment.classes_,
            yticklabels=le_sentiment.classes_)
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

